apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - monitoring-namespace.yaml
  - prometheus-rbac.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - grafana-config.yaml
  - grafana-dashboard.yaml
  - grafana-deployment.yaml

commonLabels:
  environment: production
  managed-by: kustomize
  project: catvsdog-monitoring
