apiVersion: v1
kind: Service
metadata:
  name: catvsdog-api-service
  namespace: catvsdog
  labels:
    app: catvsdog-api
spec:
  type: NodePort
  selector:
    app: catvsdog-api
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30001
  sessionAffinity: None
