apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../namespace.yaml
  - ../deployment.yaml
  - ../service.yaml
  - ../configmap.yaml
  - ../pvc.yaml
  - ../ingress.yaml
  - ../hpa.yaml

commonLabels:
  app.kubernetes.io/name: catvsdog-api
  app.kubernetes.io/component: ml-service
  app.kubernetes.io/managed-by: argocd
